"""The cross-language contract fixture (#234).

frontend/src/lifecycle.js mirrors two backend facts as literals: the seat
lifecycle states (backend/provenance.py LIFECYCLE_STATES) and the loopback
host set (backend/config.py _LOOPBACK_HOSTS). Nothing guarded that
boundary, so a backend change would leave the UI collapsing every seat to
Trial with every test green.

tests/fixtures/backend_contract.json is the committed record of those
facts. This test regenerates it from the live constants and fails when the
committed copy was stale, so the fixture update lands in the same commit
as the backend change. frontend/src/backendContract.test.js reads the same
file and asserts the JS side agrees. The fixture is committed rather than
generated on demand so `npm --prefix frontend test` passes on a clean
clone without a pytest run first.
"""
import json
from pathlib import Path

from backend import provenance, providers
from backend.config import _LOOPBACK_HOSTS

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "backend_contract.json"


def current_contract():
    return {
        "_generated_by": "tests/test_contract_fixture.py - regenerated by "
                         "running it; do not edit by hand",
        "seat_lifecycle": {
            "states": list(provenance.LIFECYCLE_STATES),
            "loopback_hosts": sorted(_LOOPBACK_HOSTS),
        },
        # The seat editor's effort dropdown and its greyed-out-model rule
        # (frontend/src/reasoningEffort.js) mirror these (#292).
        "reasoning_effort": {
            "choices": {p: list(v)
                        for p, v in sorted(providers.REASONING_CHOICES.items())},
            "anthropic_no_effort_models":
                list(providers._ANTHROPIC_NO_EFFORT_MODEL),
        },
    }


def test_committed_fixture_matches_backend_constants():
    current = json.dumps(current_contract(), indent=2, sort_keys=True) + "\n"
    committed = FIXTURE.read_text() if FIXTURE.exists() else "<missing>"
    if committed != current:
        FIXTURE.write_text(current)
        raise AssertionError(
            "tests/fixtures/backend_contract.json did not match the backend "
            "constants. It has been regenerated in place - review it, check "
            "frontend/src/backendContract.test.js still passes, and commit "
            "both sides together.")
