"""The cross-language contract fixture (#234).

frontend/src/lifecycle.js mirrors two backend facts as literals: the seat
lifecycle states (backend/provenance.py LIFECYCLE_STATES) and the loopback
host set (backend/config.py _LOOPBACK_HOSTS). Nothing guarded that
boundary, so a backend change would leave the UI collapsing every seat to
Trial with every test green.

tests/fixtures/backend_contract.json is the committed record of those
facts. This test regenerates it from the live constants and fails when the
committed copy was stale, so the fixture update lands in the same commit
as the backend change. frontend/src/backendContract.test.js reads the same
file and asserts the JS side agrees. The fixture is committed rather than
generated on demand so `npm --prefix frontend test` passes on a clean
clone without a pytest run first.
"""
import json
from pathlib import Path

from backend import passes, provenance, providers, voice
from backend.config import _LOOPBACK_HOSTS

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "backend_contract.json"

# Made up replies, each judged by backend/passes.py into the fixture, so
# frontend/src/passView.js is held to the same verdicts (#460): what the
# screen and the voice hide has to be what the engine never stores.
PASS_EXAMPLES = [
    "[pass]",
    "  [PASS]\n",
    "[pa",
    "Nothing to add from me.  [pass]",
    "The room asked us to stay quiet, so I'm passing.  [pass]",
    "Staying quiet as asked.\n\n[PASS]",
    "Holding back until someone asks me directly. [pass]",
    "I don\u2019t have anything to add. [pass]",
    "\u2026  [pass]",
    "Nothing to add. [pa",
    "You two carry on with the timber order, passing. [pass]",
    "I'll let you two carry on. [pass]",
    "Sam and Alex are sorting the clamps, not a question for me. [pass]",
    "That one wasn't aimed at us.\n\n[pass]",
    "(still listening) [pass].",
    "The glue needs 24 hours to cure.  [pass]",
    "Oil it after sanding. [PASS].",
    "Pass the glue. [pass]",
    "Nothing beats oak. [pass]",
    "Oak is not for me. [pass]",
    "Not a question for me, but the joint needs a clamp. [pass]",
    "Staying quiet, want me to check the quotes? [pass]",
    "For the record, room mode is still on.  [pass]",
    "Nothing to add, but Sam's cut list is one leg short.  [pass]",
    "Yes.  [pass]",
    "Same here.  [pass]",
    "Sand it first. [pa",
    "[pass] and one more thing",
    "Nothing to add.",
    "Sand it first.",
    "[note] something",
]


def current_contract():
    return {
        "_generated_by": "tests/test_contract_fixture.py - regenerated by "
                         "running it; do not edit by hand",
        "seat_lifecycle": {
            "states": list(provenance.LIFECYCLE_STATES),
            "loopback_hosts": sorted(_LOOPBACK_HOSTS),
        },
        # The seat editor's effort dropdown and its greyed-out-model rule
        # (frontend/src/reasoningEffort.js) mirror these (#292).
        "reasoning_effort": {
            "choices": {p: list(v)
                        for p, v in sorted(providers.REASONING_CHOICES.items())},
            "anthropic_no_effort_models":
                list(providers._ANTHROPIC_NO_EFFORT_MODEL),
        },
        # The transcript hides a seat's pass by this token and every start
        # of it (frontend/src/passView.js, #456), and a quiet remark in
        # front of it by these words (#460).
        "pass": {
            "token": passes.PASS_TOKEN,
            "quiet_phrase_pattern": passes.QUIET_PHRASE_PATTERN,
            "clause_break_pattern": passes.CLAUSE_BREAK_PATTERN,
            "quiet_max_chars": passes.QUIET_MAX_CHARS,
            "quiet_contrast": sorted(passes.QUIET_CONTRAST),
            "after_token": passes.AFTER_TOKEN,
            # The voice's pass gate is measured against this (#460):
            # TTS makes no audio until it holds this many characters.
            "tts_first_chunk_chars": json.loads(voice.tts_init_message(
                {"tts_speed": 1.0}))["generation_config"][
                    "chunk_length_schedule"][0],
            "examples": [{"text": t,
                          "is_pass": bool(passes.is_pass(t)),
                          "is_cut_pass": bool(passes.is_cut_pass(t)),
                          "kept": passes.strip_pass(t, partial=True)}
                         for t in PASS_EXAMPLES],
        },
    }


def test_committed_fixture_matches_backend_constants():
    current = json.dumps(current_contract(), indent=2, sort_keys=True) + "\n"
    committed = FIXTURE.read_text() if FIXTURE.exists() else "<missing>"
    if committed != current:
        FIXTURE.write_text(current)
        raise AssertionError(
            "tests/fixtures/backend_contract.json did not match the backend "
            "constants. It has been regenerated in place - review it, check "
            "frontend/src/backendContract.test.js still passes, and commit "
            "both sides together.")
